# Generated by Django 2.0.1 on 2018-01-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(auto_now=True)),
                ('success', models.NullBooleanField(default=None)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=250)),
                ('created', models.DateField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='scrapylog',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmon.ScrapyScript'),
        ),
    ]
