# Generated by Django 2.0.1 on 2018-01-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0003_scrapylog_log_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapylog',
            old_name='log_name',
            new_name='scrpaylog_name',
        ),
    ]
