# Generated by Django 2.0.1 on 2018-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0004_auto_20180115_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapylog',
            name='scrpaylog_name',
            field=models.CharField(max_length=200),
        ),
    ]
