# Generated by Django 2.0.1 on 2018-01-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0005_auto_20180115_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapylog',
            old_name='scrpaylog_name',
            new_name='scrapylog_name',
        ),
    ]
