# Generated by Django 2.0.1 on 2018-01-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0007_scrapylog_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyscript',
            name='project_dir',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scrapyscript',
            name='project_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scrapyscript',
            name='spider_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
