# Generated by Django 2.0.1 on 2018-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0008_auto_20180117_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyscript',
            name='run_script',
            field=models.NullBooleanField(default=None),
        ),
    ]
