# Generated by Django 2.0.1 on 2018-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0009_scrapyscript_run_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyscript',
            name='enviroment',
            field=models.CharField(default='staging', max_length=250, null=True),
        ),
    ]
