# Generated by Django 2.0.1 on 2018-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0010_scrapyscript_enviroment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyscript',
            name='recreate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapyscript',
            name='sites_new',
            field=models.TextField(default=None, null=True),
        ),
    ]
