# Generated by Django 2.0.1 on 2018-02-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0011_auto_20180205_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyscript',
            name='virtualenv',
            field=models.TextField(default=None, null=True),
        ),
    ]
