# Generated by Django 2.0.1 on 2018-02-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0012_scrapyscript_virtualenv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyerBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites_new', models.TextField(default=None, null=True)),
                ('virtualenv', models.TextField(default=None, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('batch_name', models.CharField(max_length=250)),
                ('enviroment', models.CharField(default='staging', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyerBatchScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmon.ScrapyerBatch')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmon.ScrapyScript')),
            ],
        ),
    ]
