# Generated by Django 2.0.1 on 2018-02-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0013_scrapyerbatch_scrapyerbatchscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyerbatch',
            name='run_script',
            field=models.NullBooleanField(default=None),
        ),
    ]
