# Generated by Django 2.0.1 on 2018-02-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0014_scrapyerbatch_run_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyerbatchscript',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_script', to='scrapmon.ScrapyerBatch'),
        ),
    ]
