# Generated by Django 2.0.1 on 2018-02-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0015_auto_20180226_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyerbatch',
            name='virtualenv',
        ),
    ]
