# Generated by Django 2.0.1 on 2018-03-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0016_remove_scrapyerbatch_virtualenv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapyerbatch',
            options={'verbose_name': 'Scraper Batch', 'verbose_name_plural': 'Scrapyer Batches'},
        ),
        migrations.AlterField(
            model_name='scrapyscript',
            name='recreate',
            field=models.BooleanField(default=False, verbose_name='Overwrite Existing?'),
        ),
    ]
