# Generated by Django 2.0.1 on 2018-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0017_auto_20180321_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyerbatch',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
