# Generated by Django 2.0.1 on 2018-03-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0018_scrapyerbatch_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyerbatch',
            name='recreate',
            field=models.BooleanField(default=False, verbose_name='Overwrite Existing?'),
        ),
    ]
