# Generated by Django 2.0.1 on 2018-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmon', '0019_scrapyerbatch_recreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapylog',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
